# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            cd lmk
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            cd lmk
            . venv/bin/activate
            python manage.py test
  deploy:
    docker:
     - image: google/cloud-sdk
    working_directory: ~/repo
#    machine: true
    steps:
      - run:
          name: init gcp
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: rsync static files
          command: |
            gsutil rsync -rm lmk/static/ gs://lmk-static/static
      - setup_remote_docker
      - run:
          name: build and push docker image
          command: |
            cd lmk
            docker build -t gcr.io/letmeknow-243504/lmk .
            docker push gcr.io/letmeknow-243504/lmk
      - run:
          name: deploy to gke
          command: |
            kubectl apply -f lmk.yaml




workflows:
  version: 2
  workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build